name: CI-Gestionnaire-des-Etablissements

on:
  push:
    branches: [ main]
    paths: 
      - '.github/workflows/ci.yml' 

  pull_request:
    branches: [ main]
    paths:
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gestion_des_etablissements
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: checkout code 
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'gestion_des_etablissements/requirements.txt'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests for tp python
      env: 
        DJANGO_SETTINGS_MODULE: 'gestion_des_etablissements.settings_test'
        SECRET_KEY: 'django-insecure-a!_cw%2_00^i4mg1fpdeh$8r1xs%h(5#_gusm=6i9ll)i2#yg%'
        DATABASE_URL: 'sqlite:///:memory:'
      run: |
        python manage.py test