name: CI-Gestionnaire-des-Etablissements

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'tp_python_grp3/**'
      - '.github/workflows/tp-python-ci.yml' # Aussi si le workflow lui-même change
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'tp_python_grp3/**'
      - '.github/workflows/tp-python-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tp_python_grp3
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: checkout code 
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'tp_python_grp3/requirements.txt' # Chemin vers le fichier pour le cache

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests for tp python
      env: 
        DJANGO_SETTINGS_MODULE: 'tp_python_grp3.settings_test'
        SECRET_KEY: 'django-insecure-a!_cw%2_00^i4mg1fpdeh$8r1xs%h(5#_gusm=6i9ll)i2#yg%'
        DATABASE_URL: 'sqlite:///:memory:'
      run: |
        python manage.py test